/*
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package getfood.io.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * ListItem
 */

public class ListItem {

  @SerializedName("_id")
  private String _id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("parentId")
  private String parentId = null;

  @SerializedName("checked")
  private Boolean checked = null;

  @SerializedName("checkedAt")
  private String checkedAt = null;
  public ListItem _id(String _id) {
    this._id = _id;
    return this;
  }

  

  /**
  * Get _id
  * @return _id
  **/
  @Schema(description = "")
  public String getId() {
    return _id;
  }
  public void setId(String _id) {
    this._id = _id;
  }
  public ListItem name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(example = "Burrito", required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public ListItem parentId(String parentId) {
    this.parentId = parentId;
    return this;
  }

  

  /**
  * Get parentId
  * @return parentId
  **/
  @Schema(description = "")
  public String getParentId() {
    return parentId;
  }
  public void setParentId(String parentId) {
    this.parentId = parentId;
  }
  public ListItem checked(Boolean checked) {
    this.checked = checked;
    return this;
  }

  

  /**
  * Get checked
  * @return checked
  **/
  @Schema(description = "")
  public Boolean isChecked() {
    return checked;
  }
  public void setChecked(Boolean checked) {
    this.checked = checked;
  }
  public ListItem checkedAt(String checkedAt) {
    this.checkedAt = checkedAt;
    return this;
  }

  

  /**
  * Get checkedAt
  * @return checkedAt
  **/
  @Schema(description = "")
  public String getCheckedAt() {
    return checkedAt;
  }
  public void setCheckedAt(String checkedAt) {
    this.checkedAt = checkedAt;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListItem listItem = (ListItem) o;
    return Objects.equals(this._id, listItem._id) &&
        Objects.equals(this.name, listItem.name) &&
        Objects.equals(this.parentId, listItem.parentId) &&
        Objects.equals(this.checked, listItem.checked) &&
        Objects.equals(this.checkedAt, listItem.checkedAt);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(_id, name, parentId, checked, checkedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListItem {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    checked: ").append(toIndentedString(checked)).append("\n");
    sb.append("    checkedAt: ").append(toIndentedString(checkedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
