/*
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.getfood.data.swagger.models;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ListModel
 */

public class ListModel {

  @SerializedName("_id")
  private String _id = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("color")
  private String color = null;

  @SerializedName("createdDate")
  private String createdDate = null;

  @SerializedName("createdBy")
  private User createdBy = null;

  @SerializedName("items")
  private List<ListItem> items = null;

  @SerializedName("family")
  private Family family = null;
  public ListModel _id(String _id) {
    this._id = _id;
    return this;
  }

  

  /**
  * Get _id
  * @return _id
  **/
  @Schema(description = "")
  public String getId() {
    return _id;
  }
  public void setId(String _id) {
    this._id = _id;
  }
  public ListModel title(String title) {
    this.title = title;
    return this;
  }

  

  /**
  * Get title
  * @return title
  **/
  @Schema(required = true, description = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }
  public ListModel color(String color) {
    this.color = color;
    return this;
  }

  

  /**
  * Get color
  * @return color
  **/
  @Schema(required = true, description = "")
  public String getColor() {
    return color;
  }
  public void setColor(String color) {
    this.color = color;
  }
  public ListModel createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  

  /**
  * Get createdDate
  * @return createdDate
  **/
  @Schema(description = "")
  public String getCreatedDate() {
    return createdDate;
  }
  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }
  public ListModel createdBy(User createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  

  /**
  * Get createdBy
  * @return createdBy
  **/
  @Schema(description = "")
  public User getCreatedBy() {
    return createdBy;
  }
  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }
  public ListModel items(List<ListItem> items) {
    this.items = items;
    return this;
  }

  public ListModel addItemsItem(ListItem itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<ListItem>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
  * Get items
  * @return items
  **/
  @Schema(description = "")
  public List<ListItem> getItems() {
    return items;
  }
  public void setItems(List<ListItem> items) {
    this.items = items;
  }
  public ListModel family(Family family) {
    this.family = family;
    return this;
  }

  

  /**
  * Get family
  * @return family
  **/
  @Schema(description = "")
  public Family getFamily() {
    return family;
  }
  public void setFamily(Family family) {
    this.family = family;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListModel listModel = (ListModel) o;
    return Objects.equals(this._id, listModel._id) &&
        Objects.equals(this.title, listModel.title) &&
        Objects.equals(this.color, listModel.color) &&
        Objects.equals(this.createdDate, listModel.createdDate) &&
        Objects.equals(this.createdBy, listModel.createdBy) &&
        Objects.equals(this.items, listModel.items) &&
        Objects.equals(this.family, listModel.family);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, title, color, createdDate, createdBy, items, family);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListModel {\n");

    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
