/*
 * Api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.getfood.data.swagger.models;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ListItemCreateUpdate
 */

public class ListItemCreateUpdate {

  @SerializedName("name")
  private String name = null;

  @SerializedName("checked")
  private Boolean checked = null;
  public ListItemCreateUpdate name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(example = "Burrito", required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public ListItemCreateUpdate checked(Boolean checked) {
    this.checked = checked;
    return this;
  }

  

  /**
  * Get checked
  * @return checked
  **/
  @Schema(example = "false", required = true, description = "")
  public Boolean isChecked() {
    return checked;
  }
  public void setChecked(Boolean checked) {
    this.checked = checked;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListItemCreateUpdate listItemCreateUpdate = (ListItemCreateUpdate) o;
    return Objects.equals(this.name, listItemCreateUpdate.name) &&
        Objects.equals(this.checked, listItemCreateUpdate.checked);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, checked);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListItemCreateUpdate {\n");

    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    checked: ").append(toIndentedString(checked)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
